services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      JENKINS_OPTS: --httpPort=8080
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
    depends_on:
      - dind

  dind:
    image: docker:latest
    privileged: true
    volumes:
      - /var/lib/docker

volumes:
  jenkins_home: