jenkins:
  systemMessage: "Jenkins configured using Configuration as Code"
  numExecutors: 2
  mode: NORMAL
  
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_USER}
          password: ${JENKINS_ADMIN_PASSWORD}
  
  authorizationStrategy:
    projectMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  
  clouds:
    - docker:
        name: "docker-cloud"
        dockerApi:
          dockerHost:
            uri: "tcp://dind:2375"
            credentialsId: "none"
        templates:
          - labelString: "docker-agent"
            dockerTemplateBase:
              image: "jenkins/agent:latest"
              environmentsString: |
                DOCKER_HOST=tcp://dind:2375
              mounts:
                - "type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock"
              privileged: true
            connector:
              attach:
                user: "jenkins"
            instanceCapStr: "10"

jobs:
  - script: |
      pipelineJob('k8s-deployment') {
        definition {
          cps {
            sandbox(true)
            script('''
              pipeline {
                agent {
                  label 'docker-agent'
                }
                environment {
                  KUBECONFIG = '/var/jenkins_home/.kube/config'
                }
                stages {
                  stage('Setup Environment') {
                    steps {
                      sh """
                        set -x
                        apt-get update
                        apt-get install -y wget curl
                        wget https://get.docker.com -O get-docker.sh
                        chmod +x get-docker.sh
                        ./get-docker.sh
                        docker version
                      """
                    }
                  }
                  stage('Install k3s') {
                    steps {
                      sh """
                        set -x
                        curl -sfL https://get.k3s.io | sh -
                        sleep 30
                        k3s kubectl get nodes
                      """
                    }
                  }
                  stage('Deploy Sample App') {
                    steps {
                      sh """
                        set -x
                        k3s kubectl create deployment hello-node --image=k8s.gcr.io/echoserver:1.4
                        k3s kubectl expose deployment hello-node --type=NodePort --port=8080
                        sleep 30
                        k3s kubectl get svc hello-node
                      """
                    }
                  }
                }
              }
            ''')
          }
        }
      }